apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-automount-sa-token   
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: validate-automountServiceAccountToken
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        kinds:
        - Pod
        namespaces:
        - kube-system
    preconditions:
      all:
      - key: "{{ request.\"object\".metadata.labels.\"app.kubernetes.io/part-of\" || '' }}"
        operator: NotEquals
        value: policy-reporter
    validate:
      message: "Auto-mounting of Service Account tokens is not allowed."
      pattern:
        spec:
          automountServiceAccountToken: "false"